GET http://127.0.0.1:8000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDlhNmQzZjU1MzA4NDQ5OTg5N2Q1NzgiLCJpYXQiOjE2ODc4NDIxMTEsImV4cCI6MTY4Nzg3MDkxMSwiYXVkIjoiNjQ5YTZkM2Y1NTMwODQ0OTk4OTdkNTc4IiwiaXNzIjoiYW1hcmRlZXByYW5qYW45MTFAZ21haWwuY29tIn0.NtfThlAmnZFEVwMRV1PmX50IYikC7o4G1hd1DR8Gb3M

### Register
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "amardeepranjans911@gmail.com",
    "userId": "amardeepranjan911",
    "userImage":"sfoaisfh"
}

### updateOnbaording Details
POST http://127.0.0.1:8000/user/updateOnboarding
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDlhN2Q1MmRlMTNhMWZmZjY0ZjA1YzkiLCJpYXQiOjE2ODc4NDY3MDcsImV4cCI6MTY4Nzg3NTUwNywiYXVkIjoiNjQ5YTdkNTJkZTEzYTFmZmY2NGYwNWM5IiwiaXNzIjoiYW1hcmRlZXByYW5qYW45MTFAZ21haWwuY29tIn0.WJubV_-6brsDhTWqxAonwrMSkjgcZqrnOJxYnqbsTbc
Content-Type: application/json

{
    "onBoardingCompleted": true,
    "department": "Mechanical",
    "semester": "1st-sem"
}

### saveSubject
POST http://127.0.0.1:8000/user/saveSubject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDliM2MwMzliNGMwMGUzMTE5ODEwYWIiLCJpYXQiOjE2ODc5MjQ2ODksImV4cCI6MTY4Nzk1MzQ4OSwiYXVkIjoiNjQ5YjNjMDM5YjRjMDBlMzExOTgxMGFiIiwiaXNzIjoiYW1hcmRlZXByYW5qYW45MTFAZ21haWwuY29tIn0.1LFXR4wdhTqtcDzySR7dLtcnWXt-IFoFAUlNV-brsUY
Content-Type: application/json

{"days": ["Tuesday", "Monday", "Wednesday"], "professorName": "Nirmal Hui", "subjectCode": "MEC401", "subjectName": "Solid Mecahnics"}


### FetchallSubject
GET   http://127.0.0.1:8000/user/fetchSubjects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDliM2MwMzliNGMwMGUzMTE5ODEwYWIiLCJpYXQiOjE2ODg2MjUwMDMsImV4cCI6MTY4ODY1MzgwMywiYXVkIjoiNjQ5YjNjMDM5YjRjMDBlMzExOTgxMGFiIiwiaXNzIjoiYW1hcmRlZXByYW5qYW45MTFAZ21haWwuY29tIn0.vAsCIoz7EbFTIe47vEft8Gd_5vGRKVReRr9C0Xulc6o

### updateAttendance
POST http://127.0.0.1:8000/user/updateAttendance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDliM2MwMzliNGMwMGUzMTE5ODEwYWIiLCJpYXQiOjE2ODg2MjUwMDMsImV4cCI6MTY4ODY1MzgwMywiYXVkIjoiNjQ5YjNjMDM5YjRjMDBlMzExOTgxMGFiIiwiaXNzIjoiYW1hcmRlZXByYW5qYW45MTFAZ21haWwuY29tIn0.vAsCIoz7EbFTIe47vEft8Gd_5vGRKVReRr9C0Xulc6o


